### ISSUE TITLE
smartplot.py: error: input file name missing

### ISSUE THREAD

**Issue by cdpb** [Rup0rt/smartplot#1]
I uploaded a 7MB attr.csv file to your online version and it gave me the error

_smartplot.py: error: input file name missing_

I tried again with the same file, but truncated by `tail -n 1000 attr.csv > attr.short.csv` and it works.

just wanted to let you know ...

Thanks for the work!

**Comment by Rup0rt** [comment]
Hi cdpb,

thanks for letting me know.
Problem was not in the tool itself but in reduced upload size after recent apache update. Should work again now ;)

Cheers,
Ruport

**Comment by cdpb** [comment]
I thought so too, thanks for fixing :)
